In [ ]:
#Steps for today:
#Import the data (V&J)
#Exploring the features (V&J)
#Clean and normalize the data (V&J)
#Decide on a classification algorithm (V&J)
#First trainings (V&J)
#Calculate the scoring and tweak/consolidate features accordingly (V&J)
#First submission

In [47]:
import pandas as pd
#!pip install category_encoders'
import category_encoders as ce

In [48]:
train_values = pd.read_csv('train_values.csv', sep=',')
train_labels = pd.read_csv('train_labels.csv', sep=',')
#train_labels
#train_valuesx

In [50]:
#Target encoding
#land_surface_condition, foundation_type, roof_type, ground_floor_type, other_floor_type, position, plan_configuration, legal_ownership_status,

ce_te = ce.TargetEncoder(cols=["land_surface_condition","foundation_type","roof_type","ground_floor_type","other_floor_type","position","plan_configuration","legal_ownership_status"])

#column to perform encoding
X = train_values[["land_surface_condition","foundation_type","roof_type","ground_floor_type","other_floor_type","position","plan_configuration","legal_ownership_status"]]
y = train_values['building_id']


#create an object of the Targetencoder
ce_te.fit(X,y)
t = ce_te.transform(X)
type(t)
z = train_values

# selecting old value
z[["land_surface_condition","foundation_type","roof_type","ground_floor_type","other_floor_type","position","plan_configuration","legal_ownership_status"]] = t[["land_surface_condition","foundation_type","roof_type","ground_floor_type","other_floor_type","position","plan_configuration","legal_ownership_status"]]
z
#train_values_encoded
# selecting new value
#b = t['land_surface_condition']
# replace values of one DataFrame
# with the value of another DataFrame
#df1 = train_values.replace(a,b)
# Display the Output
#display(df1)

/Users/juangbc/opt/anaconda3/lib/python3.9/site-packages/category_encoders/target_encoder.py:92: FutureWarning: Default parameter min_samples_leaf will change in version 2.6.See https://github.com/scikit-learn-contrib/category_encoders/issues/327
  warnings.warn("Default parameter min_samples_leaf will change in version 2.6."
/Users/juangbc/opt/anaconda3/lib/python3.9/site-packages/category_encoders/target_encoder.py:97: FutureWarning: Default parameter smoothing will change in version 2.6.See https://github.com/scikit-learn-contrib/category_encoders/issues/327
  warnings.warn("Default parameter smoothing will change in version 2.6."

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,802906,6,487,12198,2,30,6,5,525291.207011,526036.097182,...,0,0,0,0,0,0,0,0,0,0
1,28830,8,900,2812,2,10,8,7,523144.803391,526036.097182,...,0,0,0,0,0,0,0,0,0,0
2,94947,21,363,8973,2,10,5,5,525291.207011,526036.097182,...,0,0,0,0,0,0,0,0,0,0
3,590882,22,418,10694,2,10,6,5,525291.207011,526036.097182,...,0,0,0,0,0,0,0,0,0,0
4,201944,11,131,1488,3,30,8,9,525291.207011,526036.097182,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260596,688636,25,1335,1621,1,55,6,3,528612.309812,526036.097182,...,0,0,0,0,0,0,0,0,0,0
260597,669485,17,715,2060,2,0,6,5,525291.207011,526036.097182,...,0,0,0,0,0,0,0,0,0,0
260598,602512,17,51,8163,3,55,6,7,525291.207011,526036.097182,...,0,0,0,0,0,0,0,0,0,0
260599,151409,26,39,1851,2,10,14,6,525291.207011,526036.097182,...,0,0,0,0,0,0,0,0,0,0
260600,747594,21,9,9101,3,10,7,6,528612.309812,526036.097182,...,0,0,0,0,0,0,0,0,0,0